# SPDX-FileCopyrightText: Camden Boren
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libx11-dev libx11-xcb-dev libxkbcommon-x11-dev

      - name: Run Tests
        run: cargo test --verbose --release

      - name: Install cargo-bundle
        continue-on-error: true
        run: cargo install cargo-bundle

      - name: Build
        run: COL=80 ./script/bundle-linux

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linux-bundle
          path: target/release/bundle/deb/alc-calc_*_amd64.deb

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tests
        run: cargo test --verbose --release

      - name: Install cargo-bundle
        continue-on-error: true
        run: cargo install cargo-bundle

      - name: Set Up Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io https://cache.nixos.org/

      - name: Build
        run: nix develop .#bundle --command bash -c "COL=80 DONT_SIGN=true bundle-mac"

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: macos-bundle
          path: target/release/bundle/osx/alc-calc.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tests
        run: cargo test --verbose --release

      - name: Install Dependencies
        run: choco install boxes.portable

      - name: Install cargo-packager
        continue-on-error: true
        run: cargo install cargo-packager

      - name: Build
        run: ./script/bundle-windows.ps1

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          path: target/release/alc-calc_*_x64-setup.exe
